title: Jocab-B's Homepage
page-top-title: Jocab-B
top-section-bg-text: Steady progress leads to long-term success
home-subtitle: Yanchao Bi&ensp;|&ensp;毕研超
copyright-text: '&copy; Jocab-B 2023-2025. All Rights Reserved.'
